name: Puppeteer Script
description: An action to write Puppeteer scripts as workflows
branding:
  color: blue
  icon: globe
inputs:
  script:
    description: The script to run
    required: true
outputs:
  result:
    description: The return value of the script
runs:
  using: node16
  main: dist/index.js
