on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx prettier -c .
      - run: npm run build
      - run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: return-result
        uses: ./
        with:
          script: |
            const page = await browser.newPage();
            await page.goto('https://example.com');
            const title = await page.$eval('title', el => el.textContent);
            return { title };
      - run: test '${{ steps.return-result.outputs.result }}' = '{"title":"Example Domain"}'
