on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx prettier -c .
      - run: npm run build
      - run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-title
        uses: ./
        with:
          script: |
            const page = await browser.newPage();
            await page.goto('https://example.com');
            const title = await page.$eval('title', el => el.textContent);
            return { title };
      - run: test '${{ steps.get-title.outputs.result }}' = '{"title":"Example Domain"}'
      - id: get-body
        uses: ./
        with:
          script: |
            const page = await browser.newPage();
            await page.goto('https://example.com');
            const body = await page.$eval('body', el => el.textContent.trim());
            return body;
      - run: echo '${{ steps.get-body.outputs.result }}' | tr -d '"'
